import type { Metadata } from "next";

import "../globals.css";
import SideBar from "@/components/dashboard/SideBar";
import Copyright from "@/components/ui/Copyright";
import DashboardHeader from "@/components/dashboard/DashBoardHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = { name: "Booking" };
  const pageTitle = "Dashboard Title"
  return (
    <div className="grid grid-cols-[300px_1fr] gap-6" >
      <aside className="bg-[#111C44] shadow-lg h-screen sticky top-0"><SideBar /></aside>
      <main className="min-h-screen p-5 sm:p-10 flex flex-col gap-7">
        <DashboardHeader title={pageTitle} />
        {children}
        <Copyright store={store} />
      </main>
    </div>
  );
}