import type { Metadata } from "next";
import { Lora, Outfit } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/dashboard/SideBar";
import Breadcrumb from "@/components/ui/Breadcrumb";
import PageTitle from "@/components/ui/PageTitle";
import Personal from "@/components/dashboard/Personal";
import Copyright from "@/components/ui/Copyright";

const headingFont = Lora({
  variable: "--font-heading",
  subsets: ["latin"],
});

const bodyFont = Outfit({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = { name: "Booking" };
  return (
    <div className="grid grid-cols-[300px_1fr] gap-6" >
      <aside className="bg-[#111C44] shadow-lg h-screen sticky top-0"><SideBar /></aside>
      <main className="min-h-screen p-5 sm:p-10 flex flex-col gap-7">
        <div>
          <Breadcrumb />
          <div className="flex items-center justify-between gap-4">
            <PageTitle title="Main Dashboard" />
            <Personal />
          </div>
        </div>
        {children}
        <Copyright store={store} />
      </main>
    </div>
  );
}